In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('vgsales.csv')

In [4]:
data.head(1)

Rank        Name Platform    Year   Genre Publisher  NA_Sales  EU_Sales  \
0     1  Wii Sports      Wii  2006.0  Sports  Nintendo     41.49     29.02   

   JP_Sales  Other_Sales  Global_Sales  
0      3.77         8.46         82.74

In [5]:
# #just a list
# a=[1,2,3,4]
# b=[5,6,7,4]
#a*b  #you cant do this with list

In [12]:
#just a array.
a=np.array([1,2,3,4]) #[] is a list
b=np.array([5,6,7,4])
c=np.array([[2,3,4],[5,6,7]] ) #3D tensor, herre you can specify the data type 
print(c)
#a*b    #Its possible to multiply 

[[2 3 4]
 [5 6 7]]


array([ 5, 12, 21, 16])

In [14]:
#Get the dimension
c.ndim

2

In [15]:
# Get shape of the array
c.shape

(2, 3)

In [16]:
#CHecking the memory it takes
c.dtype

dtype('int32')

In [17]:
data.shape

(16598, 11)

In [21]:
data.iloc[2 :5]

Rank                      Name Platform    Year         Genre Publisher  \
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37